// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package worddb

import (
	"database/sql"
)

type Word struct {
	Word        string
	ZhTrans     sql.NullString
	AddedCount  sql.NullInt64
	LookupCount sql.NullInt64
}
